### ISSUE TITLE
Fork this repository!

### ISSUE THREAD

**Issue by berlinguist** [Ling-144-winter2022-team-1/team-project#4]
Please complete your Github setup for the team project by forking this repository so that you have a copy you can manipulate.

Go here: 
https://github.com/Ling-144-winter2022-team-1/team-project 
and click the 'fork' button up in the top right.

Please also refer to the following documents on Canvas:

- Setting up Your Development Environment -- section 2
- Creating a Branch on Github
- Creating & reviewing pull requests on Github

**Comment by IsaPolena** [comment]
Forked repo
